version: "3.8"

  postgres:
    image: postgres:13.3
    container_name: databasev2
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "code"
      POSTGRES_PASSWORD: "1eera4wDDDe"
    ports:
      - "5432:5432"
